Couple of fixes / improvements
gre/bezier-easing-editor pull request #8
Opened 2016-11-18 04:49 UTC by vespakoen

Hey!

I added a `npm start` script that will compile the ES6 code to ES5, I removed an unused dependency and fixed the following warning:

```
Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `BezierEditor`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

Hope you like it =)

2016-11-18 07:42 UTC, gre requested changes
yeah make sense, please remove lib/ from the committed files, i think it should probably be in .gitignore and explicitely added in package.json `files` file so lib get published, i can polish that latest.

thanks :)

2016-11-18 07:42 UTC, gre commented on lib/BezierComponent.js
> +"use strict";
please do not commit this file

2016-11-18 07:42 UTC, gre commented on lib/BezierComponent.js
> +"use strict";
I mean lib/ folder.

2016-11-18 07:46 UTC, vespakoen commented
Hmmz, the reason I added the lib folder is so I can import the module in my project.
I am using Browserify + Babel but by default, node_modules will not get "babelified".

Currently this module only makes ES6 files available through the NPM package, which is probably fine when you use something like Rollup, but not with most other packagers.

I think that lib should be included and "lib/BezierEditor.js" should even be the "main" in the package.json

2016-11-18 08:26 UTC, gre commented
I agree for the problem you are raising and also that the the "main" should point to lib/, however, lib/ should not be versioned, 
here is an example:

https://github.com/gre/react-json2d/blob/master/package.json#L5-L8

2016-11-18 08:27 UTC, gre commented
nowaday, I also tend to define a `"files"` field, that explicitely specify what should be pushed to NPM.
e.g.

```
"main": "lib/index.js",
  "files": [
    "src",
    "lib",
    "README.md"
  ],
```

2016-11-18 08:28 UTC, vespakoen commented
Oh I see what you mean, sure, I guess you can pull it in and change it on your end right?

2016-11-18 08:28 UTC, gre commented
(NB: prepublish script is implicitely called when typing `npm publish`)

2016-11-18 08:29 UTC, gre commented
as you prefer, i can refactor that project conf tonight ;)

2016-11-19 09:47 UTC, gre commented
Hi @vespakoen ,
A new version was released (0.6.0) using latest lib versions.
The npm packages is published without need to transform anything, lib/index.js is the entry, and also have the appropriate sourcemap files.

<img width="231" alt="screen shot 2016-11-19 at 10 45 45" src="https://cloud.githubusercontent.com/assets/211411/20454593/7bca3f4e-ae45-11e6-910d-1e72eaf637f0.png">


Example is also more up to date, using create-react-app bootstrap.


Cheers

2016-11-19 09:47 UTC, closed without merging